POST https://localhost/stats
Content-Type: application/json

{
  "modeName": "Spleef",
  "header": [" ", "Player", "Blocks Broken"],
  "rows": [
    ["$WIN", "asuipag", 1],
    ["$LOSS", "AASFasF", 5],
    ["$LOSS", "ASFaSFB", 5],
    ["$LOSS", "CCAS", 5],
    ["$LOSS", "ASv", 5],
    ["$LOSS", "v99ISd", 5],
    ["$CARRY", "f89123", 0],
    ["$CARRY", "Uas872", 456776],
    ["$LOSS", "897fsaf", 10]
  ]
}

###